name: Pure-Python Package Build

on:
  release:
    types: 
      - released
      - prereleased
  workflow_dispatch:

jobs:
  python-build:
    steps:
      - uses: actions/checkout@v2

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Configure conda
        uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.6
          activate-environment: release-build
          environment-file: devtools/conda-envs/release-build.yaml
          auto-activate-base: false

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list
